# Generated by Django 3.0.8 on 2020-07-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.Restaurant'),
            preserve_default=False,
        ),
    ]
